public with sharing class Calculator {
    public Calculator() {

    }
        public Integer add(Integer a , Integer b){
        
            return a+b ;

        }
        
        public integer sub(integer a,integer b){

            return a-b;

        }

        public Integer mul(integer a, integer b){

            return a*b;

        }

/*        public Integer div(integer a , integer b){

            return a/b;

        } */
    }
