
/*****************************************************************
 * Version           Date             Name        Description 
 * ***************************************************************
 * V1.0            30-03-2022        Devloper1      Addition Method
 */




public with sharing class Calculator {
    public Calculator() {

    }
    public Integer add(Integer a , Integer b){
        return a+b;
    }
        
    }

